[package]
name = "webinal"
edition.workspace = true
version.workspace = true

[dependencies]
wb-cdp = { path = "../wb-cdp" }
wb-frame = { path = "../wb-frame" }
wb-page = { path = "../wb-page" }
wb-term = { path = "../wb-term" }
anyhow.workspace = true
crossterm.workspace = true
futures-util.workspace = true
tokio.workspace = true
